import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
   
      <body className='dark:bg-slate-700'>{children}</body>

    </html>
  )
}
